import type { Lang } from "@/lib/store";

const en = {
  app: "BEM Workboard",
  tagline: "External flow → BEM settlement → machine work",
  community: "Community ledger. Not an official TapeOut plan.",
  observed: "Observed",
  pilot: "Illustrative pilot",
  observedHint: "Silicon Markets is not live. External fee converted into BEM is zero.",
  pilotHint:
    "Sample AMDB-style pool from 20 Aug. Fees, fills and destinations are internally consistent — not on-chain yet.",
  period1: "24h",
  period7: "7d",
  period30: "30d",
  navOverview: "Overview",
  navEmission: "Emission",
  navFlow: "Flow",
  navCirculation: "Supply",
  navBuilders: "Builders",
  navMethod: "Method",
  ecr: "Emission Coverage Ratio",
  ecrFormula: "ECR = BEM acquired with external, non-BEM fees ÷ new BEM emission",
  ecrZeroTitle: "No external settlement this window",
  ecrZeroBody:
    "Miners are still producing. Nothing outside TapeOut has bought BEM with a disclosed fee. That is the honest number.",
  acquired: "External BEM acquired",
  emission: "New BEM emission",
  fee: "External fees",
  volume: "Eligible volume",
  naive: "Naive stacked ‘demand’",
  naiveHint: "Acquisition + burn + lock + bounty. Same BEM counted more than once. Not demand.",
  strict: "Strict (ECR)",
  coverage: "Coverage of new emission",
  factory: "On-chain factory",
  nand: "NAND consumed",
  latch: "LATCH consumed",
  circuits: "Circuits taped",
  miners: "Avg. active miners",
  minerSells: "Est. miner sells",
  processor: "Processor sinks",
  bnn: "BNN training sinks",
  v2Pending: "V2 not live — productive BEM sinks are still zero.",
  destTitle: "Where acquired BEM went",
  destNote:
    "Destinations split one purchase. They are not additional demand. Totals equal BEM acquired.",
  retired: "Retired (burn)",
  timeLocked: "Time-locked",
  settlementLiquidity: "Settlement liquidity",
  builderBounty: "Builder bounty",
  securityReserve: "Security reserve",
  executionVault: "Execution vault",
  windows: "Buy execution",
  windowNote:
    "Batched windows, not per-swap market buys. Skip if impact or minimum fill is not met.",
  filled: "Filled",
  skipped: "Skipped",
  impact: "Impact",
  budget: "Budget",
  fill: "Fill",
  scenario: "What-if",
  scenarioLead:
    "If a community pool printed this volume every day in the selected window, with a public fee and a buy split.",
  dailyVolume: "Daily volume",
  feeBps: "Community fee",
  buyShare: "Share used to buy BEM",
  projectedEcr: "Projected ECR",
  projectedBuy: "Projected BEM bought",
  reset: "Reset",
  chartEmission: "Emission",
  chartAcquired: "External acquisition",
  chartSells: "Miner sells (est.)",
  supply: "Circulating after burns",
  locked: "Time-locked",
  burned: "Retired cumulative",
  supplyStart: "Start of window",
  supplyEnd: "End of window",
  buildersLead: "Verifiable work in the window. Bounty is a destination of acquired BEM, not a second buy.",
  kind: "Kind",
  title: "Title",
  author: "Author",
  transistors: "Transistors",
  pod: "PoD",
  bounty: "Bounty BEM",
  circuit: "Circuit",
  component: "Component",
  docs: "Docs",
  methodTitle: "How to read this board",
  method1t: "Count demand once",
  method1:
    "External fee that buys BEM is demand. Burning, locking, LP, or paying a builder is a destination of that same BEM. Summing them is an accounting trick.",
  method2t: "ECR is coverage, not a burn counter",
  method2:
    "It asks: how much of new emission was covered by actual BEM purchased with external, non-BEM economic activity?",
  method3t: "Internal loop is a different ledger",
  method3:
    "Processor spend and BNN training will be productive sinks. They matter. They are not the ECR numerator unless they are funded by external non-BEM fees.",
  method4t: "Silicon Markets is not a ticker",
  method4:
    "The test is whether semiconductor-adjacent flow can settle into BEM under public rules — not whether AMD or NVIDIA is a reserve asset.",
  method5t: "This sample is falsifiable",
  method5:
    "Observed mode is zero by construction until a hook exists. Pilot mode is a consistent illustration. If nobody trades, the experiment failed cleanly.",
  worked: "Worked example (this window)",
  notCounted: "Not counted as demand",
  counted: "Counted once",
  emptyWindows: "No execution window — nothing to buy.",
  emptyBuilders: "No taped work in this window.",
  price: "BEM mark",
  asOf: "Ledger through",
  compare: "Accounting compare",
  compareLead: "Same window, two ways of adding. Only the left column is ECR.",
  openScenario: "What-if calculator",
  close: "Close",
};

const zh: typeof en = {
  app: "BEM Workboard",
  tagline: "外部流入 → BEM 结算 → 机器工作",
  community: "社区账本。不是 TapeOut 官方计划。",
  observed: "观察值",
  pilot: "示意试点",
  observedHint: "Silicon Markets 尚未上线。外部费用换成的 BEM 为零。",
  pilotHint:
    "从 8 月 20 日起的 AMDB 风格样本池。费用、成交与去向内部自洽，链上尚未发生。",
  period1: "24小时",
  period7: "7天",
  period30: "30天",
  navOverview: "总览",
  navEmission: "排放",
  navFlow: "流向",
  navCirculation: "流通",
  navBuilders: "Builder",
  navMethod: "方法",
  ecr: "排放覆盖率",
  ecrFormula: "ECR = 外部非 BEM 费用换成的 BEM ÷ 同期新增 BEM 排放",
  ecrZeroTitle: "本窗口没有外部结算",
  ecrZeroBody:
    "矿工仍在生产。TapeOut 之外，还没有一笔可披露的费用买过 BEM。这就是诚实的数字。",
  acquired: "外部买入 BEM",
  emission: "新增 BEM 排放",
  fee: "外部费用",
  volume: "合格成交额",
  naive: "把去向再加一遍的「需求」",
  naiveHint: "买入 + 销毁 + 锁仓 + bounty。同一枚 BEM 算了多次。不是需求。",
  strict: "严格口径（ECR）",
  coverage: "对新排放的覆盖",
  factory: "链上工厂",
  nand: "NAND 消耗",
  latch: "LATCH 消耗",
  circuits: "已流片电路",
  miners: "日均在产矿机",
  minerSells: "矿工估售",
  processor: "Processor 消耗",
  bnn: "BNN 训练消耗",
  v2Pending: "V2 未上线 — 生产性 BEM 消耗仍为零。",
  destTitle: "买入的 BEM 去了哪里",
  destNote: "去向是一次购买的拆分，不是新的需求。合计等于外部买入的 BEM。",
  retired: "退出流通（销毁）",
  timeLocked: "锁仓",
  settlementLiquidity: "结算流动性",
  builderBounty: "Builder bounty",
  securityReserve: "安全储备",
  executionVault: "执行金库",
  windows: "回购执行",
  windowNote: "按窗口批量执行，而不是每笔 swap 市价买。冲击或最小成交不满足则跳过。",
  filled: "成交",
  skipped: "跳过",
  impact: "冲击",
  budget: "预算",
  fill: "成交量",
  scenario: "假如",
  scenarioLead: "若社区池在所选窗口每天都有这笔成交额，并按公开费率与买入拆分结算。",
  dailyVolume: "日成交额",
  feeBps: "社区费率",
  buyShare: "用于买入 BEM 的份额",
  projectedEcr: "推演 ECR",
  projectedBuy: "推演买入 BEM",
  reset: "重置",
  chartEmission: "排放",
  chartAcquired: "外部买入",
  chartSells: "矿工估售",
  supply: "销毁后流通",
  locked: "锁仓",
  burned: "累计退出",
  supplyStart: "窗口初",
  supplyEnd: "窗口末",
  buildersLead: "本窗口可核验的工作。Bounty 是买入 BEM 的去向，不是第二次买入。",
  kind: "类型",
  title: "名称",
  author: "作者",
  transistors: "晶体管",
  pod: "PoD",
  bounty: "Bounty BEM",
  circuit: "电路",
  component: "元件",
  docs: "文档",
  methodTitle: "怎么读这本账",
  method1t: "需求只计一次",
  method1:
    "外部费用买到 BEM 才是需求。销毁、锁仓、做市或付给 Builder，是同一枚 BEM 的去向。把它们加总是会计把戏。",
  method2t: "ECR 是覆盖率，不是销毁计数器",
  method2: "它只问：同期新增排放里，有多少被外部、非 BEM 的经济活动真正买走？",
  method3t: "内部循环是另一本账",
  method3:
    "Processor 支出和 BNN 训练将是生产性消耗。它们重要。除非由外部非 BEM 费用出资，否则不进入 ECR 分子。",
  method4t: "Silicon Markets 不是一只股票代码",
  method4:
    "要检验的是半导体相关流动能否按公开规则结算进 BEM，而不是 AMD 或 NVIDIA 会不会给 BEM 背书。",
  method5t: "这份样本必须能被证伪",
  method5:
    "观察值在 hook 出现前按构造为零。示意试点是自洽的推演。如果没人交易，实验就干净地失败。",
  worked: "本窗口的演算",
  notCounted: "不计为需求",
  counted: "只计一次",
  emptyWindows: "没有执行窗口 — 无买入。",
  emptyBuilders: "本窗口没有流片工作。",
  price: "BEM 标记价",
  asOf: "账期截至",
  compare: "口径对照",
  compareLead: "同一窗口，两种加法。只有左栏是 ECR。",
  openScenario: "假如计算器",
  close: "关闭",
};

export const copy: Record<Lang, typeof en> = { en, zh };

export function t(lang: Lang) {
  return copy[lang];
}
