/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildersRouteImport } from './routes/builders'
import { Route as CirculationRouteImport } from './routes/circulation'
import { Route as EmissionRouteImport } from './routes/emission'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as MethodRouteImport } from './routes/method'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersRoute = BuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const CirculationRoute = CirculationRouteImport.update({
  id: '/circulation',
  path: '/circulation',
  getParentRoute: () => rootRouteImport,
} as any)
const EmissionRoute = EmissionRouteImport.update({
  id: '/emission',
  path: '/emission',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builders': typeof BuildersRoute
  '/circulation': typeof CirculationRoute
  '/emission': typeof EmissionRoute
  '/flow': typeof FlowRoute
  '/method': typeof MethodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builders': typeof BuildersRoute
  '/circulation': typeof CirculationRoute
  '/emission': typeof EmissionRoute
  '/flow': typeof FlowRoute
  '/method': typeof MethodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builders': typeof BuildersRoute
  '/circulation': typeof CirculationRoute
  '/emission': typeof EmissionRoute
  '/flow': typeof FlowRoute
  '/method': typeof MethodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/builders' | '/circulation' | '/emission' | '/flow' | '/method'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builders' | '/circulation' | '/emission' | '/flow' | '/method'
  id:
    | '__root__'
    | '/'
    | '/builders'
    | '/circulation'
    | '/emission'
    | '/flow'
    | '/method'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildersRoute: typeof BuildersRoute
  CirculationRoute: typeof CirculationRoute
  EmissionRoute: typeof EmissionRoute
  FlowRoute: typeof FlowRoute
  MethodRoute: typeof MethodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders': {
      id: '/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof BuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulation': {
      id: '/circulation'
      path: '/circulation'
      fullPath: '/circulation'
      preLoaderRoute: typeof CirculationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emission': {
      id: '/emission'
      path: '/emission'
      fullPath: '/emission'
      preLoaderRoute: typeof EmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildersRoute: BuildersRoute,
  CirculationRoute: CirculationRoute,
  EmissionRoute: EmissionRoute,
  FlowRoute: FlowRoute,
  MethodRoute: MethodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
